// ignore_for_file: constant_identifier_names

part of 'app_pages.dart';

abstract class Routes {
  Routes._();

  static const SPLASH = _Paths.SPLASH;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const LOGIN = _Paths.LOGIN;
  static const REGISTER = _Paths.REGISTER;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const HOME = _Paths.HOME;
  static const DASHBOARD = _Paths.DASHBOARD;
  static const BOARDS = _Paths.BOARDS;
  static const GRADES = _Paths.GRADES;
  static const SUBJECTS = _Paths.SUBJECTS;
  static const CHAPTERS = _Paths.CHAPTERS;
  static const CHAPTER_DETAIL = _Paths.CHAPTER_DETAIL;
  static const VIDEO_PLAYER = _Paths.VIDEO_PLAYER;
  static const PROMOTIONAL_VIDEO_PLAYER = _Paths.PROMOTIONAL_VIDEO_PLAYER;
  static const DOCUMENT_VIEWER = _Paths.DOCUMENT_VIEWER;
  static const QUIZ = _Paths.QUIZ;
  static const QUIZ_RESULT = _Paths.QUIZ_RESULT;
  static const SUBSCRIPTIONS = _Paths.SUBSCRIPTIONS;
  static const SUBSCRIPTION_PLANS = _Paths.SUBSCRIPTION_PLANS;
  static const PROFILE = _Paths.PROFILE;
  static const SETTINGS = _Paths.SETTINGS;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const PROGRESS = _Paths.PROGRESS;
  static const PACKAGE_SELECTION = _Paths.PACKAGE_SELECTION;
  static const BOARD_SELECTION = _Paths.BOARD_SELECTION;
  static const SUBJECT_SELECTION = _Paths.SUBJECT_SELECTION;
  static const CHAPTER_SELECTION = _Paths.CHAPTER_SELECTION;
  static const CART = _Paths.CART;
  static const SUBJECT_CHAPTER_DETAIL = _Paths.SUBJECT_CHAPTER_DETAIL;
  static const EMAIL_VERIFICATION = _Paths.EMAIL_VERIFICATION;
  static const STUDENT_REGISTER = _Paths.STUDENT_REGISTER;
  static const STUDENT_OTP_VERIFICATION = _Paths.STUDENT_OTP_VERIFICATION;
  static const FULL_ASSESSMENT = _Paths.FULL_ASSESSMENT;
  static const PARENT_DASHBOARD = _Paths.PARENT_DASHBOARD;
  static const KID_DETAILED_PROGRESS = _Paths.KID_DETAILED_PROGRESS;
  static const MENTOR_DASHBOARD = _Paths.MENTOR_DASHBOARD;
  static const STUDENT_PROFILE = _Paths.STUDENT_PROFILE;
  static const STUDENT_PROGRESS = _Paths.STUDENT_PROGRESS;
  static const GUEST_DASHBOARD = _Paths.GUEST_DASHBOARD;
  static const CUSTOM_ASSESSMENT_CONFIG = _Paths.CUSTOM_ASSESSMENT_CONFIG;
  static const CUSTOM_ASSESSMENT = _Paths.CUSTOM_ASSESSMENT;
  static const DOWNLOADS = _Paths.DOWNLOADS;
  static const QA = _Paths.QA;
  static const BRAIN_GAMES = _Paths.BRAIN_GAMES;
  static const MENTOR_CHAT = _Paths.MENTOR_CHAT;
  static const STUDENT_COACHING = _Paths.STUDENT_COACHING;
  static const WORKSHEETS = _Paths.WORKSHEETS;
  static const WATCH_HISTORY = _Paths.WATCH_HISTORY;
  static const MY_TICKETS = _Paths.MY_TICKETS;
  static const RAISE_TICKET = _Paths.RAISE_TICKET;
  static const PAYMENT_HISTORY = _Paths.PAYMENT_HISTORY;
  static const MY_SUBSCRIPTIONS = _Paths.MY_SUBSCRIPTIONS;
  static const ALL_PACKAGES = _Paths.ALL_PACKAGES;
  static const ASSESSMENT = _Paths.ASSESSMENT;
  static const ASSESSMENT_RESULT = _Paths.ASSESSMENT_RESULT;
  static const SELF_ASSESSMENT_LIST = _Paths.SELF_ASSESSMENT_LIST;
  static const SELF_ASSESSMENT_ATTEMPT = _Paths.SELF_ASSESSMENT_ATTEMPT;
  static const SELF_ASSESSMENT_RESULT = _Paths.SELF_ASSESSMENT_RESULT;
}

abstract class _Paths {
  _Paths._();

  static const SPLASH = '/splash';
  static const ONBOARDING = '/onboarding';
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const EMAIL_VERIFICATION = '/email-verification';
  static const STUDENT_REGISTER = '/student-register';
  static const STUDENT_OTP_VERIFICATION = '/student-otp-verification';
  static const HOME = '/home';
  static const DASHBOARD = '/dashboard';
  static const BOARDS = '/boards';
  static const GRADES = '/grades';
  static const SUBJECTS = '/subjects';
  static const CHAPTERS = '/chapters';
  static const CHAPTER_DETAIL = '/chapter-detail';
  static const VIDEO_PLAYER = '/video-player';
  static const PROMOTIONAL_VIDEO_PLAYER = '/promotional-video-player';
  static const DOCUMENT_VIEWER = '/document-viewer';
  static const QUIZ = '/quiz';
  static const QUIZ_RESULT = '/quiz-result';
  static const SUBSCRIPTIONS = '/subscriptions';
  static const SUBSCRIPTION_PLANS = '/subscription-plans';
  static const PACKAGE_SELECTION = '/package-selection';
  static const BOARD_SELECTION = '/board-selection';
  static const SUBJECT_SELECTION = '/subject-selection';
  static const CHAPTER_SELECTION = '/chapter-selection';
  static const CART = '/cart';
  static const SUBJECT_CHAPTER_DETAIL = '/subject-chapter-detail';
  static const FULL_ASSESSMENT = '/full-assessment';
  static const PARENT_DASHBOARD = '/parent-dashboard';
  static const KID_DETAILED_PROGRESS = '/kid-detailed-progress';
  static const MENTOR_DASHBOARD = '/mentor-dashboard';
  static const STUDENT_PROFILE = '/student-profile';
  static const STUDENT_PROGRESS = '/student-progress';
  static const GUEST_DASHBOARD = '/guest-dashboard';
  static const CUSTOM_ASSESSMENT_CONFIG = '/custom-assessment-config';
  static const CUSTOM_ASSESSMENT = '/custom-assessment';
  static const DOWNLOADS = '/downloads';
  static const QA = '/qa';
  static const BRAIN_GAMES = '/brain-games';
  static const MENTOR_CHAT = '/mentor-chat';
  static const STUDENT_COACHING = '/student-coaching';
  static const WORKSHEETS = '/worksheets';
  static const WATCH_HISTORY = '/watch-history';
  static const MY_TICKETS = '/my-tickets';
  static const RAISE_TICKET = '/raise-ticket';
  static const PAYMENT_HISTORY = '/payment-history';
  static const MY_SUBSCRIPTIONS = '/my-subscriptions';
  static const ALL_PACKAGES = '/all-packages';
  static const PROFILE = '/profile';
  static const SETTINGS = '/settings';
  static const NOTIFICATIONS = '/notifications';
  static const PROGRESS = '/progress';
  static const ASSESSMENT = '/assessment';
  static const ASSESSMENT_RESULT = '/assessment-result';
  static const SELF_ASSESSMENT_LIST = '/self-assessment-list';
  static const SELF_ASSESSMENT_ATTEMPT = '/self-assessment-attempt';
  static const SELF_ASSESSMENT_RESULT = '/self-assessment-result';
}
